name: cashminder
description: Une application Flutter pour classifier et suivre les dépenses.

version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  charts_flutter: ^0.12.0
  csv: ^5.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.2
  mockito: ^5.4.2